"""
Rail Corrugation Detection Pipeline

Examples:

    Run Step 1:
        python main.py --step 1

    Run Step 2:
        python main.py --step 2

    Run Step 3:
        python main.py --step 3

    Run Step 4:
        python main.py --step 4

    Run everything:
        python main.py --all
"""

import argparse
from pathlib import Path

import pandas as pd

from step1_data_cleaning import (
    load_labels,
    run_step1,
)

from step2_fft_psd import run_step2
from step3_feature_engineering import run_step3
from step4_model_training import run_step4
from step5_experiments import run_step5
from step6_xgboost_refinement import run_step6


# ============================================================
# PATHS
# ============================================================

DATA_ROOT = Path(
    r"C:\Users\Ray\Desktop\hackathon\nebula"
    r"\NebulaX-Hackathon-ProblemStatement"
    r"\PS3\02_Datasets\Rail_Corrugation"
)

TRAIN_DIR = DATA_ROOT / "Train"
TEST_DIR = DATA_ROOT / "Test"

TRAIN_LABELS_PATH = (
    DATA_ROOT / "Train_Labels.csv"
)


# ============================================================
# OUTPUT DIRECTORIES
# ============================================================

OUTPUT_ROOT = Path("outputs")

STEP1_OUTPUT = OUTPUT_ROOT / "step1"
STEP2_OUTPUT = OUTPUT_ROOT / "step2"
STEP3_OUTPUT = OUTPUT_ROOT / "step3"
STEP4_OUTPUT = OUTPUT_ROOT / "step4"
STEP5_OUTPUT = OUTPUT_ROOT / "step5"
STEP6_OUTPUT = (OUTPUT_ROOT / "step6")


# ============================================================
# SAVED FILES
# ============================================================

FEATURE_FILE = (
    STEP3_OUTPUT
    / "rail_features.csv"
)


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def get_labels():
    """
    Load labels directly.

    This lets Steps 2 and 3 run without needing
    to rerun Step 1.
    """

    return load_labels(
        TRAIN_LABELS_PATH
    )


def get_features():
    """
    Load the features generated by Step 3.

    This lets Step 4 run without recalculating
    all the features.
    """

    if not FEATURE_FILE.exists():

        raise FileNotFoundError(
            "\nStep 3 feature file was not found:\n"
            f"{FEATURE_FILE}\n\n"
            "Run Step 3 first:\n"
            "    python main.py --step 3"
        )

    print(
        f"Loading saved features from:\n"
        f"{FEATURE_FILE}"
    )

    return pd.read_csv(
        FEATURE_FILE
    )


# ============================================================
# RUN INDIVIDUAL STEP
# ============================================================

def run_single_step(step):

    # --------------------------------------------------------
    # STEP 1
    # --------------------------------------------------------

    if step == 1:

        run_step1(
            train_dir=TRAIN_DIR,
            labels_path=TRAIN_LABELS_PATH,
            output_dir=STEP1_OUTPUT,
        )

    # --------------------------------------------------------
    # STEP 2
    # --------------------------------------------------------

    elif step == 2:

        labels = get_labels()

        run_step2(
            train_dir=TRAIN_DIR,
            labels=labels,
            output_dir=STEP2_OUTPUT,
        )

    # --------------------------------------------------------
    # STEP 3
    # --------------------------------------------------------

    elif step == 3:

        labels = get_labels()

        run_step3(
            train_dir=TRAIN_DIR,
            labels=labels,
            output_dir=STEP3_OUTPUT,
        )

    # --------------------------------------------------------
    # STEP 4
    # --------------------------------------------------------

    elif step == 4:

        features = get_features()

        run_step4(
            features=features,
            output_dir=STEP4_OUTPUT,
        )

    elif step == 5:

        features = get_features()

        run_step5(
            features=features,
            output_dir=STEP5_OUTPUT,
        )

    elif step == 6:

        features = get_features()

        run_step6(
            features=features,
            output_dir=STEP6_OUTPUT,
        )

    else:

        raise ValueError(
            f"Unknown step: {step}"
        )
    
    


# ============================================================
# RUN EVERYTHING
# ============================================================

def run_all():

    print()
    print("=" * 60)
    print("RAIL CORRUGATION — FULL PIPELINE")
    print("=" * 60)

    # STEP 1

    labels = run_step1(
        train_dir=TRAIN_DIR,
        labels_path=TRAIN_LABELS_PATH,
        output_dir=STEP1_OUTPUT,
    )

    # STEP 2

    run_step2(
        train_dir=TRAIN_DIR,
        labels=labels,
        output_dir=STEP2_OUTPUT,
    )

    # STEP 3

    features = run_step3(
        train_dir=TRAIN_DIR,
        labels=labels,
        output_dir=STEP3_OUTPUT,
    )

    # STEP 4

    run_step4(
        features=features,
        output_dir=STEP4_OUTPUT,
    )

    print()
    print("=" * 60)
    print("FULL PIPELINE COMPLETE")
    print("=" * 60)


# ============================================================
# COMMAND LINE
# ============================================================

def main():

    parser = argparse.ArgumentParser(
        description=(
            "Rail Corrugation Detection Pipeline"
        )
    )

    parser.add_argument(
        "--step",
        type=int,
        choices=[1, 2, 3, 4, 5, 6],
        help=(
            "Run only one pipeline step."
        ),
    )

    parser.add_argument(
        "--all",
        action="store_true",
        help=(
            "Run the complete pipeline."
        ),
    )

    args = parser.parse_args()

    # --------------------------------------------------------
    # Decide what to run
    # --------------------------------------------------------

    if args.all:

        run_all()

    elif args.step is not None:

        run_single_step(
            args.step
        )
        

    else:

        parser.print_help()


if __name__ == "__main__":
    main()